// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	OPENAI_API_KEY: string;
	SESSION_SECRETS: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_REDIRECT_URL: string;
	DB: D1Database;
}
